// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaLibros.Data;

#nullable disable

namespace TiendaLibros.Migrations
{
    [DbContext(typeof(TiendaLibrosContext))]
    [Migration("20221111063018_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TiendaLibros.Models.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Libro");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaPublicacion = new DateTime(2012, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Genero1",
                            Precio = 2400m,
                            Titulo = "Libro1"
                        },
                        new
                        {
                            Id = 2,
                            FechaPublicacion = new DateTime(2008, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Genero2",
                            Precio = 3000m,
                            Titulo = "Libro2"
                        },
                        new
                        {
                            Id = 3,
                            FechaPublicacion = new DateTime(2008, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Genero3",
                            Precio = 3000m,
                            Titulo = "Libro3"
                        },
                        new
                        {
                            Id = 4,
                            FechaPublicacion = new DateTime(2008, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Genero4",
                            Precio = 3000m,
                            Titulo = "Libro4"
                        },
                        new
                        {
                            Id = 5,
                            FechaPublicacion = new DateTime(2008, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Genero5",
                            Precio = 6000m,
                            Titulo = "Libro5"
                        },
                        new
                        {
                            Id = 6,
                            FechaPublicacion = new DateTime(2008, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Genero6",
                            Precio = 4000m,
                            Titulo = "Libro6"
                        },
                        new
                        {
                            Id = 7,
                            FechaPublicacion = new DateTime(2008, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Genero7",
                            Precio = 4500m,
                            Titulo = "Libro7"
                        },
                        new
                        {
                            Id = 8,
                            FechaPublicacion = new DateTime(2008, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Genero8",
                            Precio = 4500m,
                            Titulo = "Libro8"
                        },
                        new
                        {
                            Id = 9,
                            FechaPublicacion = new DateTime(2008, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Genero9",
                            Precio = 6600m,
                            Titulo = "Libro9"
                        },
                        new
                        {
                            Id = 10,
                            FechaPublicacion = new DateTime(2008, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Genero10",
                            Precio = 7000m,
                            Titulo = "Libro10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
